# Configuracoes da Tela 
LARGURA_TELA = 800
ALTURA_TELA = 600

# Configuracoes do Jogo 

VELOCIDADE_MAGRO = 6      
VELOCIDADE_GORDINHO = 4   
VELOCIDADE_GORDO = 2     

VELOCIDADE_ANIMACAO = 300 
TAMANHO_TILE = 64
MARGEM_CANTO = 20

# Configuracoes de Assets 
TAMANHO_FONTE_TITULO = 72
TAMANHO_FONTE_INSTRUCAO = 40
TAMANHO_FONTE_PLACAR = 36

# Configuracoes da Transicao 
WIPE_SPEED = 30 
WIPE_MAX_RADIUS = 600 
WIPE_KEY = (255, 0, 255) 

# Configuracoes de Dialogo 
TAMANHO_FONTE_DIALOGO = 28
COR_DIALOGO_FUNDO = (50, 50, 50)